/// Built-in PHP function and class stubs.
///
/// Provides arities for core PHP functions and common extensions so the
/// analyser does not flag standard-library calls as undefined.
///
/// Each entry is `(name, required_args, max_args)`.
/// `usize::MAX` means variadic (no upper bound).

/// Arity bounds for a built-in callable.
#[derive(Debug, Clone, Copy)]
pub struct Arity {
    pub required: usize,
    pub max: usize,
}

/// Look up the arity of a built-in PHP function by name.
/// Returns `None` if the name is not a known built-in.
pub fn function_arity(name: &str) -> Option<Arity> {
    BUILTIN_FUNCTIONS
        .binary_search_by_key(&name, |&(n, _, _)| n)
        .ok()
        .map(|i| {
            let (_, req, max) = BUILTIN_FUNCTIONS[i];
            Arity { required: req, max }
        })
}

/// True if `name` is a known built-in class / interface / exception.
pub fn is_builtin_class(name: &str) -> bool {
    BUILTIN_CLASSES
        .binary_search_by_key(&name, |&n| n)
        .is_ok()
}

/// Sorted list of built-in PHP function names with (required, max) arg counts.
/// `usize::MAX` means variadic. Must stay sorted for binary search.
pub static BUILTIN_FUNCTIONS: &[(&str, usize, usize)] = &[
    ("abs", 1, 1),
    ("array_chunk", 2, 3),
    ("array_column", 2, 3),
    ("array_combine", 2, 2),
    ("array_diff", 1, usize::MAX),
    ("array_diff_assoc", 1, usize::MAX),
    ("array_diff_key", 1, usize::MAX),
    ("array_fill", 3, 3),
    ("array_fill_keys", 2, 2),
    ("array_filter", 1, 3),
    ("array_flip", 1, 1),
    ("array_intersect", 1, usize::MAX),
    ("array_intersect_assoc", 1, usize::MAX),
    ("array_intersect_key", 1, usize::MAX),
    ("array_is_list", 1, 1),
    ("array_key_exists", 2, 2),
    ("array_key_first", 1, 1),
    ("array_key_last", 1, 1),
    ("array_keys", 1, 3),
    ("array_map", 2, usize::MAX),
    ("array_merge", 0, usize::MAX),
    ("array_merge_recursive", 0, usize::MAX),
    ("array_pad", 3, 3),
    ("array_pop", 1, 1),
    ("array_product", 1, 1),
    ("array_push", 1, usize::MAX),
    ("array_replace", 1, usize::MAX),
    ("array_reverse", 1, 2),
    ("array_search", 2, 3),
    ("array_shift", 1, 1),
    ("array_slice", 2, 4),
    ("array_splice", 2, 4),
    ("array_sum", 1, 1),
    ("array_unique", 1, 2),
    ("array_unshift", 1, usize::MAX),
    ("array_values", 1, 1),
    ("array_walk", 2, 3),
    ("array_walk_recursive", 2, 3),
    ("arsort", 1, 2),
    ("asort", 1, 2),
    ("base64_decode", 1, 2),
    ("base64_encode", 1, 1),
    ("base_convert", 3, 3),
    ("basename", 1, 2),
    ("bindec", 1, 1),
    ("ceil", 1, 1),
    ("checkdate", 3, 3),
    ("chr", 1, 1),
    ("chunk_split", 1, 3),
    ("class_alias", 2, 3),
    ("class_exists", 1, 2),
    ("class_implements", 1, 2),
    ("class_parents", 1, 2),
    ("closedir", 1, 1),
    ("compact", 1, usize::MAX),
    ("copy", 2, 3),
    ("count", 1, 2),
    ("crc32", 1, 1),
    ("ctype_alnum", 1, 1),
    ("ctype_alpha", 1, 1),
    ("ctype_digit", 1, 1),
    ("ctype_lower", 1, 1),
    ("ctype_print", 1, 1),
    ("ctype_punct", 1, 1),
    ("ctype_space", 1, 1),
    ("ctype_upper", 1, 1),
    ("ctype_xdigit", 1, 1),
    ("curl_close", 1, 1),
    ("curl_error", 1, 1),
    ("curl_exec", 1, 1),
    ("curl_getinfo", 1, 2),
    ("curl_init", 0, 1),
    ("curl_multi_add_handle", 2, 2),
    ("curl_multi_close", 1, 1),
    ("curl_multi_exec", 2, 2),
    ("curl_multi_getcontent", 1, 1),
    ("curl_multi_init", 0, 0),
    ("curl_multi_remove_handle", 2, 2),
    ("curl_multi_select", 1, 2),
    ("curl_setopt", 3, 3),
    ("curl_setopt_array", 2, 2),
    ("date", 1, 2),
    ("date_create", 0, 2),
    ("date_diff", 2, 3),
    ("date_format", 2, 2),
    ("date_interval_create_from_date_string", 1, 1),
    ("debug_backtrace", 0, 2),
    ("debug_print_backtrace", 0, 2),
    ("decbin", 1, 1),
    ("dechex", 1, 1),
    ("decoct", 1, 1),
    ("defined", 1, 1),
    ("dirname", 1, 2),
    ("empty", 1, 1),
    ("end", 1, 1),
    ("error_log", 1, 4),
    ("error_reporting", 0, 1),
    ("exec", 1, 3),
    ("explode", 2, 3),
    ("extension_loaded", 1, 1),
    ("extract", 1, 3),
    ("fclose", 1, 1),
    ("feof", 1, 1),
    ("fgetcsv", 1, 5),
    ("fgets", 1, 2),
    ("file", 1, 3),
    ("file_exists", 1, 1),
    ("file_get_contents", 1, 5),
    ("file_put_contents", 2, 4),
    ("fileatime", 1, 1),
    ("filectime", 1, 1),
    ("filemtime", 1, 1),
    ("fileperms", 1, 1),
    ("filesize", 1, 1),
    ("filter_has_var", 2, 2),
    ("filter_input", 2, 3),
    ("filter_input_array", 1, 2),
    ("filter_var", 1, 3),
    ("filter_var_array", 1, 2),
    ("floatval", 1, 1),
    ("floor", 1, 1),
    ("flush", 0, 0),
    ("fnmatch", 2, 3),
    ("fopen", 2, 4),
    ("fpassthru", 1, 1),
    ("fprintf", 2, usize::MAX),
    ("fputcsv", 2, 6),
    ("fread", 2, 2),
    ("fseek", 2, 3),
    ("fstat", 1, 1),
    ("ftell", 1, 1),
    ("ftruncate", 2, 2),
    ("function_exists", 1, 2),
    ("fwrite", 2, 3),
    ("get_class", 0, 1),
    ("get_class_methods", 1, 1),
    ("get_declared_classes", 0, 0),
    ("get_object_vars", 1, 1),
    ("getcwd", 0, 0),
    ("getenv", 0, 2),
    ("gethostbyaddr", 1, 1),
    ("gethostbyname", 1, 1),
    ("gethostname", 0, 0),
    ("getimagesize", 1, 2),
    ("getrandmax", 0, 0),
    ("gettimeofday", 0, 1),
    ("gettype", 1, 1),
    ("glob", 1, 2),
    ("gmdate", 1, 2),
    ("gzcompress", 1, 2),
    ("gzdeflate", 1, 2),
    ("gzencode", 1, 3),
    ("gzinflate", 1, 2),
    ("gzuncompress", 1, 2),
    ("hash", 2, 4),
    ("hash_algos", 0, 0),
    ("hash_equals", 2, 2),
    ("hash_file", 2, 3),
    ("hash_final", 1, 2),
    ("hash_hmac", 3, 4),
    ("hash_hmac_file", 3, 4),
    ("hash_init", 1, 3),
    ("hash_update", 2, 2),
    ("header", 1, 3),
    ("hexdec", 1, 1),
    ("html_entity_decode", 1, 3),
    ("htmlentities", 1, 4),
    ("htmlspecialchars", 1, 4),
    ("htmlspecialchars_decode", 1, 2),
    ("http_build_query", 1, 4),
    ("http_response_code", 0, 1),
    ("implode", 1, 2),
    ("in_array", 2, 3),
    ("inet_ntop", 1, 1),
    ("inet_pton", 1, 1),
    ("ini_get", 1, 1),
    ("ini_set", 2, 2),
    ("intdiv", 2, 2),
    ("interface_exists", 1, 2),
    ("intval", 1, 2),
    ("ip2long", 1, 1),
    ("is_a", 2, 3),
    ("is_array", 1, 1),
    ("is_bool", 1, 1),
    ("is_callable", 1, 3),
    ("is_dir", 1, 1),
    ("is_executable", 1, 1),
    ("is_file", 1, 1),
    ("is_finite", 1, 1),
    ("is_float", 1, 1),
    ("is_infinite", 1, 1),
    ("is_int", 1, 1),
    ("is_integer", 1, 1),
    ("is_link", 1, 1),
    ("is_long", 1, 1),
    ("is_nan", 1, 1),
    ("is_null", 1, 1),
    ("is_numeric", 1, 1),
    ("is_object", 1, 1),
    ("is_readable", 1, 1),
    ("is_string", 1, 1),
    ("is_subclass_of", 2, 3),
    ("is_uploaded_file", 1, 1),
    ("is_writable", 1, 1),
    ("json_decode", 1, 4),
    ("json_encode", 1, 3),
    ("json_last_error", 0, 0),
    ("json_last_error_msg", 0, 0),
    ("krsort", 1, 2),
    ("ksort", 1, 2),
    ("lcfirst", 1, 1),
    ("lcg_value", 0, 0),
    ("levenshtein", 2, 5),
    ("link", 2, 2),
    ("log", 1, 2),
    ("log10", 1, 1),
    ("long2ip", 1, 1),
    ("lstat", 1, 1),
    ("ltrim", 1, 2),
    ("max", 1, usize::MAX),
    ("mb_check_encoding", 0, 2),
    ("mb_convert_case", 2, 3),
    ("mb_convert_encoding", 2, 3),
    ("mb_detect_encoding", 1, 3),
    ("mb_internal_encoding", 0, 1),
    ("mb_list_encodings", 0, 0),
    ("mb_strimwidth", 2, 4),
    ("mb_stripos", 2, 4),
    ("mb_stristr", 2, 4),
    ("mb_strlen", 1, 2),
    ("mb_strpos", 2, 4),
    ("mb_strripos", 2, 4),
    ("mb_strrpos", 2, 4),
    ("mb_strstr", 2, 4),
    ("mb_strtolower", 1, 2),
    ("mb_strtoupper", 1, 2),
    ("mb_substr", 2, 4),
    ("mb_substr_count", 2, 3),
    ("md5", 1, 2),
    ("metaphone", 1, 2),
    ("method_exists", 2, 2),
    ("microtime", 0, 1),
    ("min", 1, usize::MAX),
    ("mkdir", 1, 4),
    ("mktime", 0, 6),
    ("move_uploaded_file", 2, 2),
    ("mt_getrandmax", 0, 0),
    ("mt_rand", 0, 2),
    ("mt_srand", 0, 2),
    ("nl2br", 1, 2),
    ("number_format", 1, 4),
    ("ob_end_clean", 0, 0),
    ("ob_end_flush", 0, 0),
    ("ob_get_clean", 0, 0),
    ("ob_get_contents", 0, 0),
    ("ob_start", 0, 3),
    ("octdec", 1, 1),
    ("opendir", 1, 2),
    ("openssl_decrypt", 3, 6),
    ("openssl_encrypt", 3, 6),
    ("openssl_random_pseudo_bytes", 1, 2),
    ("ord", 1, 1),
    ("pack", 1, usize::MAX),
    ("parse_ini_file", 1, 3),
    ("parse_ini_string", 1, 3),
    ("parse_str", 2, 2),
    ("parse_url", 1, 2),
    ("password_algos", 0, 0),
    ("password_get_info", 1, 1),
    ("password_hash", 2, 3),
    ("password_needs_rehash", 2, 3),
    ("password_verify", 2, 2),
    ("pathinfo", 1, 2),
    ("phpversion", 0, 1),
    ("pi", 0, 0),
    ("pos", 1, 1),
    ("pow", 2, 2),
    ("preg_grep", 2, 3),
    ("preg_last_error", 0, 0),
    ("preg_last_error_msg", 0, 0),
    ("preg_match", 2, 5),
    ("preg_match_all", 2, 5),
    ("preg_quote", 1, 2),
    ("preg_replace", 3, 5),
    ("preg_replace_callback", 3, 5),
    ("preg_split", 2, 4),
    ("print_r", 1, 2),
    ("property_exists", 2, 2),
    ("random_bytes", 1, 1),
    ("random_int", 2, 2),
    ("range", 2, 3),
    ("rawurldecode", 1, 1),
    ("rawurlencode", 1, 1),
    ("readdir", 0, 1),
    ("readfile", 1, 3),
    ("realpath", 1, 1),
    ("rename", 2, 3),
    ("reset", 1, 1),
    ("rewinddir", 0, 1),
    ("rmdir", 1, 2),
    ("round", 1, 3),
    ("rsort", 1, 2),
    ("rtrim", 1, 2),
    ("scandir", 1, 3),
    ("serialize", 1, 1),
    ("session_destroy", 0, 0),
    ("session_id", 0, 1),
    ("session_name", 0, 1),
    ("session_start", 0, 1),
    ("set_error_handler", 1, 2),
    ("set_exception_handler", 1, 1),
    ("set_time_limit", 1, 1),
    ("setcookie", 1, 7),
    ("settype", 2, 2),
    ("sha1", 1, 2),
    ("shell_exec", 1, 1),
    ("similar_text", 2, 3),
    ("sleep", 1, 1),
    ("sort", 1, 2),
    ("soundex", 1, 1),
    ("sprintf", 1, usize::MAX),
    ("sqrt", 1, 1),
    ("srand", 0, 2),
    ("sscanf", 2, usize::MAX),
    ("stat", 1, 1),
    ("str_contains", 2, 2),
    ("str_ends_with", 2, 2),
    ("str_getcsv", 1, 4),
    ("str_ireplace", 3, 4),
    ("str_pad", 2, 4),
    ("str_repeat", 2, 2),
    ("str_replace", 3, 4),
    ("str_split", 1, 2),
    ("str_starts_with", 2, 2),
    ("str_word_count", 1, 3),
    ("strcasecmp", 2, 2),
    ("strcmp", 2, 2),
    ("strip_tags", 1, 2),
    ("stripos", 2, 3),
    ("stripslashes", 1, 1),
    ("stristr", 2, 3),
    ("strlen", 1, 1),
    ("strncasecmp", 3, 3),
    ("strncmp", 3, 3),
    ("strpbrk", 2, 2),
    ("strpos", 2, 3),
    ("strrchr", 2, 2),
    ("strrev", 1, 1),
    ("strripos", 2, 3),
    ("strrpos", 2, 3),
    ("strstr", 2, 3),
    ("strtok", 1, 2),
    ("strtolower", 1, 1),
    ("strtotime", 1, 2),
    ("strtoupper", 1, 1),
    ("strval", 1, 1),
    ("substr", 2, 3),
    ("substr_count", 2, 4),
    ("substr_replace", 3, 4),
    ("symlink", 2, 2),
    ("sys_get_temp_dir", 0, 0),
    ("tempnam", 2, 2),
    ("time", 0, 0),
    ("tmpfile", 0, 0),
    ("touch", 1, 3),
    ("trigger_error", 1, 2),
    ("trim", 1, 2),
    ("uasort", 2, 2),
    ("ucfirst", 1, 1),
    ("ucwords", 1, 2),
    ("uksort", 2, 2),
    ("uniqid", 0, 2),
    ("unlink", 1, 2),
    ("unserialize", 1, 2),
    ("urldecode", 1, 1),
    ("urlencode", 1, 1),
    ("usleep", 1, 1),
    ("usort", 2, 2),
    ("var_dump", 1, usize::MAX),
    ("var_export", 1, 2),
    ("version_compare", 2, 3),
    ("wordwrap", 1, 4),
];

/// Sorted list of built-in PHP class / interface / exception names.
static BUILTIN_CLASSES: &[&str] = &[
    "ArrayAccess",
    "ArrayIterator",
    "ArrayObject",
    "BadFunctionCallException",
    "BadMethodCallException",
    "Closure",
    "Countable",
    "CurlHandle",
    "DOMAttr",
    "DOMDocument",
    "DOMElement",
    "DOMException",
    "DOMNode",
    "DOMNodeList",
    "DOMText",
    "DOMXPath",
    "DateInterval",
    "DateTime",
    "DateTimeImmutable",
    "DateTimeInterface",
    "DateTimeZone",
    "DirectoryIterator",
    "DomainException",
    "Error",
    "Exception",
    "Fiber",
    "FiberError",
    "FilesystemIterator",
    "Generator",
    "GlobIterator",
    "HashContext",
    "InfiniteIterator",
    "IntlChar",
    "InvalidArgumentException",
    "Iterator",
    "IteratorAggregate",
    "JsonException",
    "JsonSerializable",
    "LengthException",
    "LogicException",
    "OutOfBoundsException",
    "OutOfRangeException",
    "OverflowException",
    "PDO",
    "PDOException",
    "PDOStatement",
    "RangeException",
    "RecursiveArrayIterator",
    "RecursiveDirectoryIterator",
    "RecursiveIterator",
    "RecursiveIteratorIterator",
    "ReflectionClass",
    "ReflectionException",
    "ReflectionFunction",
    "ReflectionMethod",
    "ReflectionNamedType",
    "ReflectionParameter",
    "ReflectionProperty",
    "ReflectionType",
    "ReflectionUnionType",
    "RuntimeException",
    "Serializable",
    "SimpleXMLElement",
    "SimpleXMLIterator",
    "SplDoublyLinkedList",
    "SplFileInfo",
    "SplFileObject",
    "SplFixedArray",
    "SplHeap",
    "SplMaxHeap",
    "SplMinHeap",
    "SplObjectStorage",
    "SplPriorityQueue",
    "SplQueue",
    "SplStack",
    "Stringable",
    "Throwable",
    "TypeError",
    "UnderflowException",
    "UnexpectedValueException",
    "ValueError",
    "WeakMap",
    "WeakReference",
    "XMLReader",
    "XMLWriter",
    "ZipArchive",
    "mysqli",
    "mysqli_driver",
    "mysqli_result",
    "mysqli_stmt",
    "stdClass",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_functions_are_sorted() {
        for pair in BUILTIN_FUNCTIONS.windows(2) {
            assert!(
                pair[0].0 <= pair[1].0,
                "out of order: '{}' before '{}'",
                pair[0].0,
                pair[1].0
            );
        }
    }

    #[test]
    fn builtin_classes_are_sorted() {
        for pair in BUILTIN_CLASSES.windows(2) {
            assert!(pair[0] <= pair[1], "out of order: '{}' before '{}'", pair[0], pair[1]);
        }
    }

    #[test]
    fn strlen_is_known() {
        assert!(function_arity("strlen").is_some());
    }

    #[test]
    fn pdo_is_builtin_class() {
        assert!(is_builtin_class("PDO"));
    }

    #[test]
    fn unknown_function_is_none() {
        assert!(function_arity("totally_unknown_fn_xyz").is_none());
    }
}
